"""Pydantic models for IB ORB Trading Bot.

Data contracts between services:
- ORBRange: Opening range boundaries and metadata
- FuturesMarketState: Real-time market snapshot with indicators
- ORBSetup: Trade setup candidate from ORB strategy
- TradeIntent: Sized and approved trade ready for execution
- Position: Open position tracking
- TradeSetup: Generic trade setup from any strategy (LLM, scanner, etc.)
"""

from datetime import datetime, timezone
from decimal import Decimal
from pydantic import BaseModel, Field

from ib_bot.core.enums import Direction, SessionPhase, SetupType


class ORBRange(BaseModel):
    """Opening Range boundaries calculated from first N minutes of session.

    Published on Topic.OPENING_RANGE once the OR period ends.
    """

    symbol: str = Field(..., description="Futures symbol (e.g., ES, NQ)")
    or_high: Decimal = Field(..., ge=0, description="Opening range high")
    or_low: Decimal = Field(..., ge=0, description="Opening range low")
    midpoint: Decimal = Field(..., ge=0, description="OR midpoint: (high + low) / 2")
    range_ticks: int = Field(..., ge=0, description="OR range in ticks")
    volume: Decimal = Field(..., ge=0, description="Volume during OR period")
    vwap: Decimal = Field(..., ge=0, description="VWAP during OR period")
    timestamp: datetime = Field(..., description="OR calculation timestamp")
    valid: bool = Field(default=True, description="Whether OR is valid for trading")

    class Config:
        json_encoders = {
            Decimal: lambda v: float(v),
            datetime: lambda v: v.isoformat(),
        }


class FuturesMarketState(BaseModel):
    """Real-time market state for a futures contract.

    Published on Topic.MARKET_DATA at regular intervals.
    """

    symbol: str = Field(..., description="Futures symbol (e.g., ES, NQ)")
    last_price: Decimal = Field(..., ge=0, description="Last traded price")
    vwap: Decimal = Field(..., ge=0, description="Session VWAP")
    atr_14: Decimal = Field(..., ge=0, description="ATR(14)")
    volume: Decimal = Field(..., ge=0, description="Session volume")
    session_phase: SessionPhase = Field(..., description="Current session phase")
    timestamp: datetime = Field(..., description="State timestamp")

    class Config:
        json_encoders = {
            Decimal: lambda v: float(v),
            datetime: lambda v: v.isoformat(),
        }


class ORBSetup(BaseModel):
    """ORB trade setup candidate generated by strategy.

    Published on Topic.SIGNAL when an ORB breakout is detected.
    """

    symbol: str = Field(..., description="Futures symbol")
    direction: Direction = Field(..., description="Trade direction")
    setup_type: SetupType = Field(..., description="ORB setup type")
    entry_price: Decimal = Field(..., ge=0, description="Breakout entry price")
    stop_price: Decimal = Field(..., ge=0, description="Stop loss price")
    target_price: Decimal = Field(..., ge=0, description="Profit target price")
    risk_ticks: int = Field(..., ge=0, description="Risk in ticks (entry to stop)")
    reward_ticks: int = Field(..., ge=0, description="Reward in ticks (entry to target)")
    or_range: ORBRange = Field(..., description="Opening range used for setup")
    confidence: Decimal = Field(..., ge=0, le=1, description="Setup confidence 0-1")

    class Config:
        json_encoders = {
            Decimal: lambda v: float(v),
            datetime: lambda v: v.isoformat(),
        }


class TradeIntent(BaseModel):
    """Sized and approved trade ready for execution.

    Published on Topic.ORDER after risk approval and position sizing.
    """

    setup: ORBSetup = Field(..., description="Original ORB setup")
    contracts: int = Field(..., gt=0, description="Number of contracts to trade")
    risk_usd: Decimal = Field(..., ge=0, description="Total risk in USD")
    timestamp: datetime = Field(..., description="Intent creation timestamp")

    class Config:
        json_encoders = {
            Decimal: lambda v: float(v),
            datetime: lambda v: v.isoformat(),
        }


class Position(BaseModel):
    """Open position tracking.

    Published on Topic.POSITION when positions change.
    """

    symbol: str = Field(..., description="Futures symbol")
    direction: Direction = Field(..., description="Trade direction")
    entry_price: Decimal = Field(..., ge=0, description="Average entry price")
    contracts: int = Field(..., gt=0, description="Number of contracts")
    stop_price: Decimal = Field(..., ge=0, description="Current stop price")
    target_price: Decimal = Field(..., ge=0, description="Current target price")
    unrealized_pnl: Decimal = Field(..., description="Unrealized P&L in USD")
    entry_time: datetime = Field(..., description="Position entry timestamp")

    class Config:
        json_encoders = {
            Decimal: lambda v: float(v),
            datetime: lambda v: v.isoformat(),
        }


class TradeSetup(BaseModel):
    """Generic trade setup from any strategy (LLM, scanner, manual).

    Published on Topic.LLM_SIGNAL when the LLM equity strategy
    produces an actionable trade. Can also be used by other
    non-ORB strategies that target stocks/ETFs.
    """

    symbol: str = Field(..., description="Ticker symbol (e.g., AAPL, SPY, ES)")
    asset_class: str = Field(
        default="equity", description="Asset class: equity, etf, futures"
    )
    direction: Direction = Field(..., description="Trade direction")
    setup_type: SetupType = Field(..., description="Setup type identifier")
    entry_price: Decimal = Field(..., gt=0, description="Entry price")
    stop_price: Decimal = Field(..., gt=0, description="Stop loss price")
    target_price: Decimal = Field(..., gt=0, description="Take profit price")
    confidence: Decimal = Field(
        default=Decimal("0.5"), ge=0, le=1, description="Signal confidence 0-1"
    )
    source: str = Field(
        default="llm_equity", description="Signal source (llm_equity, scanner, manual)"
    )

    class Config:
        json_encoders = {
            Decimal: lambda v: float(v),
        }


class StockTradeIntent(BaseModel):
    """Trade intent for stocks/ETFs, sized in shares.

    Published on Topic.ORDER when the scanner+LLM pipeline
    produces an actionable trade for an equity instrument.
    """

    symbol: str = Field(..., description="Ticker symbol (e.g., AAPL, SPY)")
    direction: Direction = Field(..., description="Trade direction")
    shares: int = Field(..., gt=0, description="Number of shares to trade")
    entry_price: Decimal = Field(..., gt=0, description="Limit entry price")
    stop_price: Decimal = Field(..., gt=0, description="Stop loss price")
    target_price: Decimal = Field(..., gt=0, description="Take profit price")
    risk_usd: Decimal = Field(..., ge=0, description="Total risk in USD")
    confidence: Decimal = Field(
        default=Decimal("0.5"), ge=0, le=1, description="Signal confidence 0-1"
    )
    source: str = Field(
        default="scanner", description="Signal source (scanner, llm_equity, manual)"
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(tz=timezone.utc),
        description="Intent creation timestamp",
    )

    class Config:
        json_encoders = {
            Decimal: lambda v: float(v),
            datetime: lambda v: v.isoformat(),
        }
