"""Initial schema

Revision ID: f41a369f1467
Revises:
Create Date: 2025-10-31 17:51:14.328451+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f41a369f1467"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crypto_klines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("period", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("high", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("low", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("volume", sa.Numeric(precision=30, scale=8), nullable=False),
        sa.Column("amount", sa.Numeric(precision=30, scale=8), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "period", "timestamp", name="uq_kline_symbol_period_time"),
    )
    op.create_index("idx_klines_lookup", "crypto_klines", ["symbol", "period"], unique=False)
    op.create_index(
        "idx_klines_unique", "crypto_klines", ["symbol", "period", "timestamp"], unique=True
    )
    op.create_index(op.f("ix_crypto_klines_id"), "crypto_klines", ["id"], unique=False)
    op.create_table(
        "crypto_prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("price_date", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "price_date", name="uq_price_symbol_date"),
    )
    op.create_index("idx_prices_lookup", "crypto_prices", ["symbol"], unique=False)
    op.create_index("idx_prices_unique", "crypto_prices", ["symbol", "price_date"], unique=True)
    op.create_index(op.f("ix_crypto_prices_id"), "crypto_prices", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_index("idx_users_email", "users", ["email"], unique=False)
    op.create_index("idx_users_username", "users", ["username"], unique=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("account_type", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("base_url", sa.String(length=500), nullable=True),
        sa.Column("api_key", sa.String(length=500), nullable=True),
        sa.Column("initial_capital", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("current_cash", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("frozen_cash", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_accounts_type", "accounts", ["account_type"], unique=False)
    op.create_index("idx_accounts_user_active", "accounts", ["user_id", "is_active"], unique=False)
    op.create_index(op.f("ix_accounts_id"), "accounts", ["id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("order_no", sa.String(length=100), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("side", sa.String(length=10), nullable=False),
        sa.Column("order_type", sa.String(length=20), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("filled_quantity", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_no"),
    )
    op.create_index("idx_orders_account", "orders", ["account_id"], unique=False)
    op.create_index("idx_orders_created", "orders", ["created_at"], unique=False)
    op.create_index("idx_orders_order_no", "orders", ["order_no"], unique=True)
    op.create_index("idx_orders_status", "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=False)
    op.create_table(
        "positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("available_quantity", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("average_cost", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_positions_account", "positions", ["account_id"], unique=False)
    op.create_index(
        "idx_positions_account_symbol", "positions", ["account_id", "symbol"], unique=True
    )
    op.create_index(op.f("ix_positions_id"), "positions", ["id"], unique=False)
    op.create_table(
        "ai_decision_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("decision_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.String(length=2000), nullable=False),
        sa.Column("operation", sa.String(length=10), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("prev_portion", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("target_portion", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("total_balance", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("executed", sa.Boolean(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_ai_logs_account", "ai_decision_logs", ["account_id"], unique=False)
    op.create_index("idx_ai_logs_time", "ai_decision_logs", ["decision_time"], unique=False)
    op.create_index(op.f("ix_ai_decision_logs_id"), "ai_decision_logs", ["id"], unique=False)
    op.create_table(
        "trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("side", sa.String(length=10), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("commission", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("trade_time", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_trades_account", "trades", ["account_id"], unique=False)
    op.create_index(
        "idx_trades_dedup", "trades", ["trade_time", "symbol", "quantity", "price"], unique=True
    )
    op.create_index("idx_trades_order", "trades", ["order_id"], unique=False)
    op.create_index("idx_trades_time", "trades", ["trade_time"], unique=False)
    op.create_index(op.f("ix_trades_id"), "trades", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trades_id"), table_name="trades")
    op.drop_index("idx_trades_time", table_name="trades")
    op.drop_index("idx_trades_order", table_name="trades")
    op.drop_index("idx_trades_dedup", table_name="trades")
    op.drop_index("idx_trades_account", table_name="trades")
    op.drop_table("trades")
    op.drop_index(op.f("ix_ai_decision_logs_id"), table_name="ai_decision_logs")
    op.drop_index("idx_ai_logs_time", table_name="ai_decision_logs")
    op.drop_index("idx_ai_logs_account", table_name="ai_decision_logs")
    op.drop_table("ai_decision_logs")
    op.drop_index(op.f("ix_positions_id"), table_name="positions")
    op.drop_index("idx_positions_account_symbol", table_name="positions")
    op.drop_index("idx_positions_account", table_name="positions")
    op.drop_table("positions")
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_index("idx_orders_status", table_name="orders")
    op.drop_index("idx_orders_order_no", table_name="orders")
    op.drop_index("idx_orders_created", table_name="orders")
    op.drop_index("idx_orders_account", table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_accounts_id"), table_name="accounts")
    op.drop_index("idx_accounts_user_active", table_name="accounts")
    op.drop_index("idx_accounts_type", table_name="accounts")
    op.drop_table("accounts")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index("idx_users_username", table_name="users")
    op.drop_index("idx_users_email", table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_crypto_prices_id"), table_name="crypto_prices")
    op.drop_index("idx_prices_unique", table_name="crypto_prices")
    op.drop_index("idx_prices_lookup", table_name="crypto_prices")
    op.drop_table("crypto_prices")
    op.drop_index(op.f("ix_crypto_klines_id"), table_name="crypto_klines")
    op.drop_index("idx_klines_unique", table_name="crypto_klines")
    op.drop_index("idx_klines_lookup", table_name="crypto_klines")
    op.drop_table("crypto_klines")
    # ### end Alembic commands ###
