"""Add daily learning reports

Revision ID: c18829e9861f
Revises: f41a369f1467
Create Date: 2025-11-20 17:04:11.010918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18829e9861f'
down_revision: Union[str, Sequence[str], None] = 'f41a369f1467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_learning_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('skill_metrics', sa.JSON(), nullable=False),
    sa.Column('deepseek_analysis', sa.JSON(), nullable=False),
    sa.Column('suggested_weights', sa.JSON(), nullable=True),
    sa.Column('suggested_prompt_changes', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'report_date', name='uq_daily_report_account_date')
    )
    op.create_index('idx_daily_reports_analyzed_at', 'daily_learning_reports', ['analyzed_at'], unique=False)
    op.create_index('idx_daily_reports_date', 'daily_learning_reports', ['report_date'], unique=False)
    op.create_index('idx_daily_reports_status', 'daily_learning_reports', ['status'], unique=False)
    op.create_index(op.f('ix_daily_learning_reports_id'), 'daily_learning_reports', ['id'], unique=False)
    op.create_index(op.f('ix_daily_learning_reports_status'), 'daily_learning_reports', ['status'], unique=False)
    with op.batch_alter_table('decision_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analyzed_in_daily_report_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_decision_snapshot_daily_report', 'daily_learning_reports', ['analyzed_in_daily_report_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint('fk_decision_snapshot_daily_report', type_='foreignkey')
        batch_op.drop_column('analyzed_in_daily_report_id')
    op.drop_index(op.f('ix_daily_learning_reports_status'), table_name='daily_learning_reports')
    op.drop_index(op.f('ix_daily_learning_reports_id'), table_name='daily_learning_reports')
    op.drop_index('idx_daily_reports_status', table_name='daily_learning_reports')
    op.drop_index('idx_daily_reports_date', table_name='daily_learning_reports')
    op.drop_index('idx_daily_reports_analyzed_at', table_name='daily_learning_reports')
    op.drop_table('daily_learning_reports')
    # ### end Alembic commands ###
