"""Pydantic models for HLQuantBot conservative refactor.

These models define the data contracts between services:
- MarketState: OHLCV + indicators for an asset
- Setup: Trade setup candidate
- TradeIntent: Sized and approved trade ready for execution
- RiskParams: Risk management parameters
"""

from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Optional, List
from pydantic import BaseModel, Field, field_validator


class Regime(str, Enum):
    """Market regime classification."""

    TREND = "trend"      # ADX > 25, clear directional movement
    RANGE = "range"      # ADX < 20, sideways/mean-reverting
    CHAOS = "chaos"      # Uncertain, no clear pattern - stay flat


class Direction(str, Enum):
    """Trade direction."""

    LONG = "long"
    SHORT = "short"
    FLAT = "flat"


class SetupType(str, Enum):
    """Type of trade setup."""

    TREND_BREAKOUT = "trend_breakout"      # Breakout in trend regime
    MEAN_REVERSION = "mean_reversion"      # Bounce in range regime
    MOMENTUM = "momentum"                   # Momentum continuation


class KillSwitchStatus(str, Enum):
    """Kill switch status levels."""

    OK = "ok"                    # Trading normally
    WARNING = "warning"          # Approaching limits
    DAILY_PAUSE = "daily_pause"  # Paused until tomorrow
    WEEKLY_PAUSE = "weekly_pause"  # Paused for 3 days
    STOPPED = "stopped"          # Max DD hit - manual intervention needed


# =============================================================================
# Core Data Models
# =============================================================================

class MarketState(BaseModel):
    """Market state for a single asset with OHLCV and indicators.

    Published on Topic.MARKET_STATE every 4h (or configured interval).
    """

    symbol: str = Field(..., description="Trading symbol (e.g., BTC, ETH)")
    timeframe: str = Field(default="4h", description="Candle timeframe")
    timestamp: datetime = Field(..., description="State timestamp")

    # OHLCV
    open: Decimal = Field(..., ge=0)
    high: Decimal = Field(..., ge=0)
    low: Decimal = Field(..., ge=0)
    close: Decimal = Field(..., ge=0)
    volume: Decimal = Field(..., ge=0)

    # Technical Indicators
    atr: Decimal = Field(..., ge=0, description="ATR(14)")
    atr_pct: Decimal = Field(..., ge=0, description="ATR as % of price")
    adx: Decimal = Field(..., ge=0, le=100, description="ADX(14)")
    rsi: Decimal = Field(..., ge=0, le=100, description="RSI(14)")
    ema50: Decimal = Field(..., ge=0, description="EMA(50)")
    ema200: Decimal = Field(..., ge=0, description="EMA(200)")
    ema200_slope: Decimal = Field(..., description="EMA200 slope (normalized)")

    # Optional indicators
    choppiness: Optional[Decimal] = Field(None, ge=0, le=100, description="Choppiness Index")
    bb_upper: Optional[Decimal] = Field(None, ge=0, description="Bollinger upper band")
    bb_lower: Optional[Decimal] = Field(None, ge=0, description="Bollinger lower band")
    bb_mid: Optional[Decimal] = Field(None, ge=0, description="Bollinger middle band")

    # Derived
    regime: Regime = Field(..., description="Detected market regime")
    trend_direction: Direction = Field(..., description="Current trend direction")

    # Metadata
    bars_count: int = Field(default=200, description="Number of bars used")

    class Config:
        json_encoders = {
            Decimal: lambda v: float(v),
            datetime: lambda v: v.isoformat(),
        }


class Setup(BaseModel):
    """Trade setup candidate generated by strategy.

    Published on Topic.SETUPS when a valid setup is detected.
    """

    id: str = Field(..., description="Unique setup ID")
    symbol: str = Field(..., description="Trading symbol")
    timestamp: datetime = Field(..., description="Setup generation time")

    # Setup details
    setup_type: SetupType = Field(..., description="Type of setup")
    direction: Direction = Field(..., description="Trade direction")
    regime: Regime = Field(..., description="Regime at setup time")

    # Price levels
    entry_price: Decimal = Field(..., ge=0, description="Target entry price")
    stop_price: Decimal = Field(..., ge=0, description="Initial stop loss")
    stop_distance_pct: Decimal = Field(..., description="Stop distance as %")

    # Indicators at setup time
    atr: Decimal = Field(..., ge=0)
    adx: Decimal = Field(..., ge=0, le=100)
    rsi: Decimal = Field(..., ge=0, le=100)

    # Quality metrics
    setup_quality: Decimal = Field(default=Decimal("0.5"), ge=0, le=1,
                                   description="Setup quality score 0-1")
    confidence: Decimal = Field(default=Decimal("0.5"), ge=0, le=1,
                                description="Strategy confidence 0-1")

    # LLM veto (filled after veto check)
    llm_approved: Optional[bool] = Field(None, description="LLM approval status")
    llm_confidence: Optional[Decimal] = Field(None, ge=0, le=1)
    llm_reason: Optional[str] = Field(None)

    class Config:
        json_encoders = {
            Decimal: lambda v: float(v),
            datetime: lambda v: v.isoformat(),
        }


class RiskParams(BaseModel):
    """Risk parameters for position sizing.

    Calculated by RiskManager based on setup and account state.
    """

    # Sizing
    risk_amount: Decimal = Field(..., ge=0, description="Max risk in USD")
    position_size: Decimal = Field(..., ge=0, description="Position size in base")
    notional_value: Decimal = Field(..., ge=0, description="Notional value in USD")

    # Stop levels
    stop_price: Decimal = Field(..., ge=0)
    stop_distance_pct: Decimal = Field(...)
    trailing_distance_atr: Decimal = Field(default=Decimal("2.5"))

    # Exposure checks
    exposure_pct: Decimal = Field(..., ge=0, le=100,
                                  description="Position as % of equity")
    total_exposure_pct: Decimal = Field(..., ge=0,
                                        description="Total portfolio exposure %")
    leverage_used: Decimal = Field(default=Decimal("1"), ge=0)

    # Validation flags
    size_approved: bool = Field(default=True)
    rejection_reason: Optional[str] = Field(None)

    class Config:
        json_encoders = {
            Decimal: lambda v: float(v),
        }


class TradeIntent(BaseModel):
    """Trade intent ready for execution.

    Published on Topic.TRADE_INTENT after sizing and approval.
    Contains everything needed to execute the trade.
    """

    id: str = Field(..., description="Intent ID (matches Setup ID)")
    setup_id: str = Field(..., description="Original setup ID")
    symbol: str = Field(...)
    timestamp: datetime = Field(...)

    # Trade parameters
    direction: Direction = Field(...)
    setup_type: SetupType = Field(...)

    # Execution parameters
    entry_price: Decimal = Field(..., ge=0, description="Target entry")
    position_size: Decimal = Field(..., ge=0, description="Size to trade")
    notional_value: Decimal = Field(..., ge=0)

    # Stop parameters
    stop_price: Decimal = Field(..., ge=0)
    trailing_atr_mult: Decimal = Field(default=Decimal("2.5"))

    # Risk info
    risk_amount: Decimal = Field(..., ge=0)
    risk_pct: Decimal = Field(..., ge=0, le=100)

    # Order preferences
    prefer_limit: bool = Field(default=True)
    max_slippage_pct: Decimal = Field(default=Decimal("0.1"))

    class Config:
        json_encoders = {
            Decimal: lambda v: float(v),
            datetime: lambda v: v.isoformat(),
        }


class LLMDecision(BaseModel):
    """LLM veto decision for a setup.

    Stored for analysis and accuracy tracking.
    """

    setup_id: str = Field(...)
    timestamp: datetime = Field(...)

    # Decision
    decision: str = Field(..., pattern="^(ALLOW|DENY)$")
    confidence: Decimal = Field(..., ge=0, le=1)
    reason: str = Field(...)

    # Context at decision time
    symbol: str = Field(...)
    regime: Regime = Field(...)
    setup_type: SetupType = Field(...)

    # Outcome tracking (filled after trade closes)
    trade_pnl: Optional[Decimal] = Field(None)
    was_correct: Optional[bool] = Field(None)

    class Config:
        json_encoders = {
            Decimal: lambda v: float(v),
            datetime: lambda v: v.isoformat(),
        }


class EquitySnapshot(BaseModel):
    """Equity curve snapshot for risk monitoring."""

    timestamp: datetime = Field(...)
    equity: Decimal = Field(..., ge=0)

    # Drawdown tracking
    peak_equity: Decimal = Field(..., ge=0)
    drawdown_pct: Decimal = Field(..., ge=0, le=100)

    # Daily/Weekly P&L
    daily_pnl: Decimal = Field(default=Decimal("0"))
    daily_pnl_pct: Decimal = Field(default=Decimal("0"))
    weekly_pnl: Decimal = Field(default=Decimal("0"))
    weekly_pnl_pct: Decimal = Field(default=Decimal("0"))

    # Position info
    positions_count: int = Field(default=0, ge=0)
    total_exposure: Decimal = Field(default=Decimal("0"), ge=0)

    # Kill switch status
    kill_switch_status: KillSwitchStatus = Field(default=KillSwitchStatus.OK)

    class Config:
        json_encoders = {
            Decimal: lambda v: float(v),
            datetime: lambda v: v.isoformat(),
        }


# =============================================================================
# Order Models
# =============================================================================

class Order(BaseModel):
    """Order model for execution tracking."""

    id: str = Field(..., description="Local order ID")
    exchange_id: Optional[str] = Field(None, description="Exchange order ID")
    intent_id: str = Field(..., description="TradeIntent ID")

    symbol: str = Field(...)
    direction: Direction = Field(...)
    order_type: str = Field(...)  # OrderType as string

    # Order details
    size: Decimal = Field(..., ge=0)
    price: Optional[Decimal] = Field(None, ge=0)

    # Status
    status: str = Field(default="pending")  # OrderStatus as string
    filled_size: Decimal = Field(default=Decimal("0"), ge=0)
    filled_price: Optional[Decimal] = Field(None, ge=0)

    # Timestamps
    created_at: datetime = Field(...)
    submitted_at: Optional[datetime] = Field(None)
    filled_at: Optional[datetime] = Field(None)

    # Execution quality
    slippage_pct: Optional[Decimal] = Field(None)
    fees: Decimal = Field(default=Decimal("0"))

    class Config:
        json_encoders = {
            Decimal: lambda v: float(v),
            datetime: lambda v: v.isoformat(),
        }


class Position(BaseModel):
    """Open position model."""

    symbol: str = Field(...)
    direction: Direction = Field(...)

    # Size and prices
    size: Decimal = Field(..., ge=0)
    entry_price: Decimal = Field(..., ge=0)
    current_price: Decimal = Field(..., ge=0)

    # Stop management
    stop_price: Decimal = Field(..., ge=0)
    highest_price: Decimal = Field(..., ge=0)  # For trailing
    lowest_price: Decimal = Field(..., ge=0)   # For trailing shorts

    # P&L
    unrealized_pnl: Decimal = Field(...)
    unrealized_pnl_pct: Decimal = Field(...)

    # Metadata
    setup_id: str = Field(...)
    setup_type: SetupType = Field(...)
    opened_at: datetime = Field(...)

    class Config:
        json_encoders = {
            Decimal: lambda v: float(v),
            datetime: lambda v: v.isoformat(),
        }
